### ISSUE TITLE
Improve test coverage to test request headers and body

### ISSUE THREAD

**Issue by oliverbrooks** [pearlshare/mailchimp-client#1]
Current tests check that the appropriate MC method/url are hit.  Should add additional checks for headers and body contents.

**Comment by pasupulaphani** [comment]
upgraded tests to check auth header. Fix is available from version 0.0.8

https://github.com/pearlshare/mailchimp-client/commit/ffdf5df3522e1399cd8c93a329c0e280d549a73f
